"""add reset token columns

Revision ID: 0690b2864c37
Revises: 6eaea5dbaf78
Create Date: 2026-02-13 00:47:05.966722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0690b2864c37'
down_revision = '6eaea5dbaf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('blocks_json', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_templates_coach_id'), ['coach_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_templates_coach_id'))

    op.drop_table('session_templates')
    # ### end Alembic commands ###
