"""add periodization_cycles table

Revision ID: 8e45cc751021
Revises: ecec777d5a97
Create Date: 2026-02-13 02:06:10.378895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e45cc751021'
down_revision = 'ecec777d5a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodization_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cycle_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('planned_load', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['periodization_cycles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('periodization_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodization_cycles_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periodization_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodization_cycles_team_id'))

    op.drop_table('periodization_cycles')
    # ### end Alembic commands ###
