"""add seasons model and team.season_id

Revision ID: 909ceaffcf85
Revises: e40fb50b477f
Create Date: 2026-02-13 01:05:49.586143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909ceaffcf85'
down_revision = 'e40fb50b477f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_coach_id'), ['coach_id'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_teams_season_id'), ['season_id'], unique=False)
        batch_op.create_foreign_key('fk_teams_season_id', 'seasons', ['season_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_season_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_teams_season_id'))
        batch_op.drop_column('season_id')

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_coach_id'))

    op.drop_table('seasons')
    # ### end Alembic commands ###
