"""add attendance model and uploads

Revision ID: e40fb50b477f
Revises: 0690b2864c37
Create Date: 2026-02-13 00:56:39.082307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40fb50b477f'
down_revision = '0690b2864c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes_trained', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('minutes_trained')

    # ### end Alembic commands ###
